# Generated by Django 4.0.5 on 2022-06-06 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Ответ')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Вес ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('many_answers', models.BooleanField(default=False, verbose_name='Несколько правильных ответов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_test_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала теста')),
                ('finish_test_time', models.DateTimeField(null=True, verbose_name='Время завершения теста')),
                ('amount', models.SmallIntegerField(default=0, verbose_name='Сумма баллов')),
                ('answers', models.ManyToManyField(related_name='results', to='questions.answer', verbose_name='Выбранные ответы')),
                ('users', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ('-finish_test_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('text'), name='Не уникальный вопрос'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('text__length__gt', 0)), name='Короткткий вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Вопрос к этому ответу'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('text', 'questions'), name='Одинаковые ответы у вопроса'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(check=models.Q(('text__length__gt', 0)), name='Пустой ответ'),
        ),
    ]
